//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UseCase5.Specs.DataGeneratorReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketData", Namespace="http://schemas.datacontract.org/2004/07/DataGeneratorServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class MarketData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImpliedVolatilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StockPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImpliedVolatility {
            get {
                return this.ImpliedVolatilityField;
            }
            set {
                if ((this.ImpliedVolatilityField.Equals(value) != true)) {
                    this.ImpliedVolatilityField = value;
                    this.RaisePropertyChanged("ImpliedVolatility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double StockPrice {
            get {
                return this.StockPriceField;
            }
            set {
                if ((this.StockPriceField.Equals(value) != true)) {
                    this.StockPriceField = value;
                    this.RaisePropertyChanged("StockPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataGeneratorReference.IDataGeneratorService")]
    public interface IDataGeneratorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataGeneratorService/GetData", ReplyAction="http://tempuri.org/IDataGeneratorService/GetDataResponse")]
        UseCase5.Specs.DataGeneratorReference.MarketData GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataGeneratorService/GetData", ReplyAction="http://tempuri.org/IDataGeneratorService/GetDataResponse")]
        System.Threading.Tasks.Task<UseCase5.Specs.DataGeneratorReference.MarketData> GetDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataGeneratorServiceChannel : UseCase5.Specs.DataGeneratorReference.IDataGeneratorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataGeneratorServiceClient : System.ServiceModel.ClientBase<UseCase5.Specs.DataGeneratorReference.IDataGeneratorService>, UseCase5.Specs.DataGeneratorReference.IDataGeneratorService {
        
        public DataGeneratorServiceClient() {
        }
        
        public DataGeneratorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataGeneratorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataGeneratorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataGeneratorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UseCase5.Specs.DataGeneratorReference.MarketData GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<UseCase5.Specs.DataGeneratorReference.MarketData> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
    }
}
